import './style.css';
import {createGame,advance,dispatch,quote,income,capacity,stage,prestigeQuote,has} from './engine';
import {MODELS,BUSINESSES,GPUS,UPGRADES,HARNESS,PERKS,NEWS,STAGES,WORKER_PRICES} from './content';
import {encodeSave,decodeSave,clockStep} from './save';
import {drawRoom,roomStatus,resetRoomTransitions} from './room';
import {productionStatus,projectedIncome,suggestedUpgrades,modelPreview,upgradePreview} from './presentation';
import {ICONS} from './icons';
import {createUiState,legacyTab,type Drawer} from './ui-state';
import type {GameState,Action} from './types';

declare global {interface Window {advanceTime:(ms:number)=>void;render_game_to_text:()=>string}}
const SAVE_KEY='bedroom-agi-v1',ui=createUiState();
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n>=100?0:2}).format(n);
const number=(n:number)=>Math.floor(n).toLocaleString('en-US');
const clock=(n:number)=>`${Math.floor(n/3600).toString().padStart(2,'0')}:${Math.floor(n/60%60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const text=(id:string,value:string)=>{const el=$(id);if(el.textContent!==value)el.textContent=value;};
const hidden=(id:string,value:boolean)=>{$(id).hidden=value;};
const width=(id:string,value:number)=>{$(id).style.width=`${Math.max(0,Math.min(100,value))}%`;};
const badge=(id:string)=>`<span class="illustrated-icon"><img src="${ICONS[id]??''}" alt="" loading="eager"><span class="icon-fallback" aria-hidden="true">${id==='slopclaw'?'⌁':'◇'}</span></span>`;
const buy=(label:string,type:string,id='',cls='secondary')=>`<button class="${cls}" data-action="${type}" data-id="${id}" data-key="${type}-${id}">${label}</button>`;
let state=createGame(),lastWall=Date.now(),offlineSummary='',saveWarning='',endingShown=false,preserveInvalidSave=false,drawerOpener:HTMLElement|null=null,modalOpener:HTMLElement|null=null,confirmationOpener:HTMLElement|null=null;
try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const saved=decodeSave(raw,Date.now());if(saved){state=saved.state;lastWall=Math.max(lastWall,saved.savedAt);const before=state.cash,slop=state.slop;advance(state,saved.offlineSeconds);if(saved.offlineSeconds>30)offlineSummary=`While you were away: ${number(state.slop-slop)} posts, ${money(state.cash-before)} net. ${Math.round(saved.offlineSeconds/60)} minutes counted (two-hour cap).`;}else{preserveInvalidSave=true;saveWarning='Your old save couldn’t be read. A fresh run is ready; the old save has been kept until you make a move.';}}}catch{saveWarning='This browser won’t let us save locally. Export your save before closing.';}
if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)state.reducedMotion=true;

function catalogue(name:string){return `<details class="catalogue" data-disclosure="catalogue-${name}" id="catalogue-${name}"><summary>Show complete catalogue</summary><small>Includes future choices and owned equipment.</small></details>`;}
function benefit(kind:string){return kind==='speed'?'15% faster production':kind==='pay'?'20% added payout':kind==='reach'?'16% added payout':'More cooling';}
function upgradeMarkup(id:string,place:string){const u=UPGRADES.find(u=>u.id===id)!;return `<article class="choice-row upgrade-row" id="${place}-upgrade-${id}"><div><h3>${u.name}</h3><p>${u.description}</p><small>${benefit(u.kind)} · ${u.rank+1}/6</small></div>${buy(money(u.cost),'upgrade',u.id)}</article>`;}
function drawerMarkup(){return `<section data-drawer-panel="Businesses"><p class="drawer-intro">Completed content sells automatically. Switching changes the next job.</p>${catalogue('Businesses')}<div class="catalogue-list">${BUSINESSES.map(b=>`<article class="choice-row business-card" id="business-${b.id}"><span class="business-symbol">${b.icon}</span><div><h3>${b.name}</h3><p>${b.description}</p><small id="business-${b.id}-detail"></small></div>${buy('Select','business',b.id)}</article>`).join('')}</div></section>
 <section data-drawer-panel="Models"><p class="drawer-intro">Estimates use your current business. Running jobs keep their original model.</p>${catalogue('Models')}<div class="catalogue-list">${MODELS.map(m=>`<article class="choice-row model-card" id="model-${m.id}">${badge(m.id)}<div><h3>${m.name}</h3><small class="company">${m.company} · ${m.tag}</small><p>${m.description}</p><strong class="estimate" id="model-${m.id}-net"></strong><small id="model-${m.id}-detail"></small><small id="model-${m.id}-quant" class="warning" hidden>Quantized: payout reduced by 18%.</small>${buy('Use model','model',m.id)}</div></article>`).join('')}</div><p class="fine-print">Fictional models and prices. No requests leave your browser. Local models pay electricity per job and reserve VRAM per worker.</p></section>
 <section data-drawer-panel="Rig"><p class="drawer-intro">Install a better rig to fit larger models and speed up local jobs.</p><div class="hardware-summary"><span>VRAM <strong id="rig-capacity"></strong></span><span>Temperature <strong id="rig-heat"></strong></span><span>Local load <strong id="rig-watts"></strong></span></div>${catalogue('Rig')}<div class="catalogue-list">${GPUS.map(g=>`<article class="choice-row hardware-row" id="gpu-${g.id}">${badge(g.id)}<div><h3>${g.name}</h3><p>${g.description}</p><small>${g.vram} GB · ${g.speed}× local speed · ${g.watts} W</small>${buy(money(g.cost),'gpu',g.id)}</div></article>`).join('')}</div><h3 class="subheading">Memory and cooling</h3><article class="choice-row" id="quantization-row"><div><h3>Quantization</h3><p>Halves VRAM when a model won’t fit. Payout drops 18%.</p></div>${buy('$300','harness','quantization')}</article><div class="catalogue-list">${UPGRADES.filter(u=>u.kind==='cool').map(u=>upgradeMarkup(u.id,'rig')).join('')}</div></section>
 <section data-drawer-panel="Agents"><div class="claw-banner">${badge('slopclaw')}<div><h3>SlopClaw</h3><p id="claw-description"></p>${buy('Install · $2,400','claw')}</div></div><div class="worker-panel"><div><h3 id="worker-count"></h3><p>Workers share the rig and add coordination costs.</p></div>${buy('Add worker','worker')}</div><h3 class="subheading">Routing</h3><div class="routing-grid">${([['manual','Your choice','Use the selected model.'],['cheapest','Cheapest','Lowest affordable running cost.'],['margin','Highest margin','Best estimated net income per worker.'],['local','Local first','Prefer local; use cloud if needed.']] as const).map(([id,name,description])=>`<button class="route-card" data-action="routing" data-id="${id}" data-key="routing-${id}"><strong>${name}</strong><span>${description}</span></button>`).join('')}</div><p id="routing-hint" class="hint"></p><details data-disclosure="harness"><summary>Harness upgrades</summary><div class="details-content">${HARNESS.filter(h=>h.id!=='quantization').map(h=>`<article class="choice-row"><div><h3>${h.name}</h3><p>${h.description}</p></div>${buy(money(h.cost),'harness',h.id)}</article>`).join('')}</div></details></section>
 <section data-drawer-panel="Upgrades"><p class="drawer-intro">Production improvements apply to new jobs. Owned upgrades and later levels are in the catalogue.</p>${catalogue('Upgrades')}<div class="catalogue-list">${UPGRADES.filter(u=>u.kind!=='cool').map(u=>upgradeMarkup(u.id,'all')).join('')}</div><p class="fine-print">Cooling and quantization are in <button class="text-button" data-drawer="Rig">Rig ↗</button>.</p></section>
 <section data-drawer-panel="Funding"><div class="funding-card"><span id="funding-round" class="micro"></span><h3 id="funding-name"></h3><p id="funding-copy"></p><div class="funding-amount"><strong id="funding-earned"></strong><span id="funding-target"></span></div><div class="meter"><i id="funding-progress"></i></div><div class="funding-reward"><span>Valuation at this raise</span><strong id="funding-reward"></strong></div>${buy('Keep earning','raise','','primary')}<p class="fine-print">Resets cash, rig, businesses, models, workers and regular upgrades. Keeps permanent perks, discoveries and lifetime stats.</p></div><section id="permanent-perks" hidden><div class="section-heading"><h3>Permanent upgrades</h3><strong id="valuation"></strong></div><p class="drawer-intro">Production perks apply immediately. Starting equipment arrives next run.</p>${catalogue('Funding')}<div class="catalogue-list">${PERKS.map(p=>`<article class="choice-row perk-card" id="perk-${p.id}"><div><small>${p.tier===1?'SEED ROUND':'SERIES A'}</small><h3>${p.name}</h3><p>${p.description}</p></div>${buy(`${p.cost} UV`,'perk',p.id)}</article>`).join('')}</div></section><p class="lifetime" id="lifetime"></p></section>`;}

document.querySelector('#app')!.innerHTML=`
 <header class="site-header"><a class="wordmark" href="#" aria-label="Bedroom AGI home">Bedroom <em>AGI.</em></a><div class="header-finances"><strong id="cash" aria-label="Cash"></strong><details id="income-disclosure" data-disclosure="income"><summary><span id="net"></span><span class="income-unit"> / sec</span><span aria-hidden="true">⌄</span></summary><div class="income-popover"><span>Revenue <strong id="revenue"></strong></span><span>Operating costs <strong id="cost"></strong></span><small>Current running jobs. Costs are paid when each job starts.</small></div></details></div><div class="header-tools"><button id="funding-open" class="secondary" data-drawer="Funding">Funding <span id="funding-percent"></span></button><button id="settings" class="icon-button" aria-label="Open settings">⚙</button></div></header>
 <main><div id="offline" class="offline" hidden><span id="offline-text"></span><button id="dismiss-offline" aria-label="Dismiss message">×</button></div><div class="game-layout"><section class="room-card"><canvas id="room" width="720" height="480" role="img" aria-label="An illustrated bedroom with a person at a laptop"></canvas><div class="room-caption"><div><span class="micro" id="stage-index"></span><h2 id="stage-name"></h2></div><button class="text-button" data-drawer="Rig">View rig ↗</button></div><p id="room-warning" class="room-warning" hidden></p></section>
 <section class="production-card" aria-labelledby="production-heading"><div class="production-heading"><h1 id="production-heading">Production</h1><button class="text-button" id="agents-open" data-drawer="Agents" hidden>Agents ↗</button></div><div class="production-selectors"><button id="business-select" class="selector" data-drawer="Businesses"><small>BUSINESS</small><strong id="business-name"></strong><span id="business-chevron" aria-hidden="true">⌄</span></button><button id="model-select" class="selector" data-drawer="Models"><small>NEXT JOB MODEL</small><strong id="model-name"></strong><span id="model-chevron" aria-hidden="true">⌄</span></button></div><p id="route-label" class="route-label" hidden></p><div class="production-metrics"><span><strong id="job-payout"></strong> payout</span><span><strong id="job-duration"></strong> / job</span></div><div class="job-progress"><div><span id="production-status"></span><span id="job-countdown"></span></div><div class="meter"><i id="job-progress"></i></div></div><p id="production-reason" class="production-reason" hidden></p><button id="recover" class="secondary recovery" data-action="recover" hidden>Use free chatbot + SEO</button><div class="production-buttons"><button id="generate" data-action="generate" data-key="generate-" class="primary">Generate slop <span aria-hidden="true">→</span></button><button id="automate" data-action="auto" data-key="auto-" class="secondary" hidden>Automate · $25</button><span id="automatic-label" hidden>Running automatically</span></div><p id="first-hint" class="hint">Generate two articles, then buy automatic production for $25.</p><details id="production-details" data-disclosure="production"><summary>Production details</summary><div class="details-content"><p id="production-cost"></p><p id="production-projected"></p><div class="worker-jobs">${Array.from({length:4},(_,i)=>`<div id="job-${i}" class="worker-job"><span id="job-${i}-label"></span><div class="meter"><i id="job-${i}-progress"></i></div></div>`).join('')}</div><button id="manual-extra" data-action="generate-extra" class="secondary" hidden>Generate one extra job</button><p id="action-message" role="status"></p></div></details></section></div>
 <section class="suggestions" aria-labelledby="upgrades-heading"><div class="section-heading"><h2 id="upgrades-heading">Upgrades</h2><button class="text-button" data-drawer="Upgrades">All upgrades ↗</button></div><div class="suggestion-grid">${[0,1].map(i=>`<article class="suggestion" id="suggestion-${i}" hidden><div><strong id="suggestion-${i}-name"></strong><p id="suggestion-${i}-copy"></p><small id="suggestion-${i}-benefit"></small></div><button class="secondary" id="suggestion-${i}-buy" data-action="upgrade"></button></article>`).join('')}</div><p id="upgrades-complete" hidden>No production upgrades left. Cooling is in Rig.</p></section><section class="activity" aria-labelledby="activity-heading"><div class="section-heading"><h2 id="activity-heading">Activity</h2><span id="log-status" class="micro"></span></div><article class="news-card"><span id="news-kind" class="news-eyebrow"></span><h3 id="news-title"></h3><p id="news-copy"></p><small id="news-modifier" hidden></small></article><details data-disclosure="logs"><summary>Recent production logs</summary><div id="feed" class="feed-list">${Array.from({length:5},(_,i)=>`<div id="feed-${i}" class="log-line"><time id="feed-${i}-time"></time><span id="feed-${i}-text"></span></div>`).join('')}</div></details></section><footer><span>Fictional prices, performance & executive dialogue.</span><button id="about" class="text-button">How to play</button></footer></main>
 <dialog id="drawer" aria-labelledby="drawer-heading"><div class="drawer-header"><h2 id="drawer-heading" tabindex="-1"></h2><button id="close-drawer" class="icon-button" aria-label="Close details">×</button></div><div id="drawer-body">${drawerMarkup()}</div></dialog><dialog id="dialog" aria-labelledby="modal-heading"><div id="dialog-body"></div></dialog><dialog id="confirmation" aria-labelledby="confirmation-heading"><div id="confirmation-body"></div></dialog><div id="announcement" class="sr-only" aria-live="polite"></div>`;

function updateButton(type:string,id:string,label:string,disabled:boolean,selected=false){document.querySelectorAll<HTMLButtonElement>(`[data-action="${type}"][data-id="${id}"]`).forEach(b=>{if(b.textContent!==label)b.textContent=label;b.disabled=disabled;b.setAttribute('aria-pressed',String(selected));});}
function catalogueOpen(name:string){return Boolean(ui.disclosures[`catalogue-${name}`]);}
function row(id:string,visible:boolean,selected=false,order=0){const el=$(id);el.hidden=!visible;el.classList.toggle('selected',selected);el.style.order=String(order);}
function render(){
 const rates=income(state),p=prestigeQuote(state),status=productionStatus(state),q=status.quote,projection=projectedIncome(state),business=BUSINESSES.find(b=>b.id===state.business)!,model=MODELS.find(m=>m.id===status.model)!;
 text('cash',money(state.cash));text('net',`${rates.net>=0?'+':''}${money(rates.net)}`);text('revenue',`${money(rates.revenue)}/s`);text('cost',`${money(rates.cost)}/s`);text('funding-percent',`${Math.floor(state.runEarned/p.target*100)}%`);$('funding-open').classList.toggle('ready',p.eligible);
 text('stage-index',`BEDROOM ${stage(state)+1} / 6`);text('stage-name',STAGES[stage(state)]);hidden('room-warning',state.heat<=65);text('room-warning','Local jobs are slowing down. View rig to buy more cooling.');
 text('business-name',business.name);text('model-name',model.name);const businessChoices=BUSINESSES.filter(b=>state.runEarned>=b.unlock).length>1,modelChoices=MODELS.filter(m=>state.runEarned>=m.unlock).length>1;$<HTMLButtonElement>('business-select').disabled=!businessChoices;$<HTMLButtonElement>('model-select').disabled=!modelChoices;hidden('business-chevron',!businessChoices);hidden('model-chevron',!modelChoices);
 hidden('route-label',state.routing==='manual'||!state.claw||!has(state,'routing'));text('route-label',`Routing: ${{manual:'Your choice',cheapest:'Cheapest',margin:'Highest margin',local:'Local first'}[state.routing]} · changes apply to new jobs`);
 text('job-payout',money(q.payout));text('job-duration',`${q.duration.toFixed(1)}s`);const next=state.jobs.reduce<GameState['jobs'][number]|undefined>((a,j)=>!a||j.remaining<a.remaining?j:a,undefined);text('production-status',status.kind==='paused'?'Production paused':state.jobs.length?`${state.jobs.length} ${state.jobs.length===1?'job':'jobs'} running`:state.auto?'Starting next job':'Ready for a job');text('job-countdown',next?`${next.remaining.toFixed(1)}s to sale`:'');width('job-progress',next?(1-next.remaining/next.duration)*100:0);
 const warning=status.kind==='paused'||status.kind==='waiting-for-vram'?status.reason:q.available&&q.net<0?'You’re spending more on requests than you’re making.':'';hidden('production-reason',!warning);text('production-reason',warning);hidden('recover',!status.recoverable);const busy=state.jobs.length>=state.workers;hidden('generate',state.auto);$<HTMLButtonElement>('generate').disabled=busy||!q.available||q.cost>state.cash;text('generate',busy?'Working…':'Generate slop →');hidden('automate',state.auto||state.cash<25);hidden('automatic-label',!state.auto||status.kind==='paused');hidden('first-hint',state.auto);text('first-hint',state.cash>=25?'Automatic production is affordable. Buy it and stop clicking.':'Generate two articles, then buy automatic production for $25.');hidden('agents-open',!state.claw&&state.runEarned<8000);hidden('manual-extra',!state.auto);$<HTMLButtonElement>('manual-extra').disabled=busy||!q.available||q.cost>state.cash;
 text('production-cost',`Next job costs ${money(q.cost)}. Revenue ${money(q.payout)}; net ${money(q.payout-q.cost)}.`);text('production-projected',`Next-job estimate: ${money(projection.net)}/s across ${projection.slots} ${projection.slots===1?'worker':'workers'}. Running jobs keep their original price and duration.`);text('action-message',state.notice);
 for(let i=0;i<4;i++){hidden(`job-${i}`,i>=state.workers);const j=state.jobs.find(j=>j.worker===i);text(`job-${i}-label`,j?`Worker ${i+1} · ${MODELS.find(m=>m.id===j.model)!.name} · ${j.remaining.toFixed(1)}s · ${money(j.cost)} cost`:`Worker ${i+1} · waiting`);width(`job-${i}-progress`,j?(1-j.remaining/j.duration)*100:0);}
 const suggestions=suggestedUpgrades(state);for(let i=0;i<2;i++){const u=suggestions[i];hidden(`suggestion-${i}`,!u);if(!u)continue;text(`suggestion-${i}-name`,u.name);text(`suggestion-${i}-copy`,u.description);const preview=upgradePreview(state,u.id);text(`suggestion-${i}-benefit`,preview.reserveReason||(state.cash<u.cost?`Save ${money(u.cost-state.cash)} more · ${benefit(u.kind)}`:benefit(u.kind)));const b=$<HTMLButtonElement>(`suggestion-${i}-buy`);b.dataset.id=u.id;b.dataset.key=`suggestion-${u.id}`;b.disabled=state.cash<u.cost;if(b.textContent!==money(u.cost))b.textContent=money(u.cost);}hidden('upgrades-complete',suggestions.length>0);
 const news=NEWS.find(n=>n.id===state.event)??NEWS.find(n=>n.id===state.discovered.at(-1));text('news-kind',news?.speaker?`${news.speaker} · FICTIONAL DIALOGUE`:'FICTIONAL INDUSTRY UPDATE');text('news-title',news?.title??'The work used to go to someone else.');text('news-copy',news?.text??'A client wants articles without paying a writer. You have a laptop and no questions about the arrangement.');hidden('news-modifier',!state.eventLeft||!news||news.effect==='none');text('news-modifier',`${news?.effect==='demand'?'Payouts +15%':'Running costs +12%'} · ${Math.ceil(state.eventLeft)}s left`);text('log-status',`${number(state.slop)} published`);
 for(let i=0;i<5;i++){const f=state.feed[i];hidden(`feed-${i}`,!f);if(f){text(`feed-${i}-time`,clock(f.at));text(`feed-${i}-text`,f.text);}}const message=offlineSummary||saveWarning;hidden('offline',!message);text('offline-text',message);if(ui.drawer)updateDrawer();if(state.ending&&!endingShown){endingShown=true;showEnding();}
}
function updateDrawer(){
 const panel=ui.drawer!,all=catalogueOpen(panel),p=prestigeQuote(state);text('drawer-heading',panel);document.querySelectorAll<HTMLElement>('[data-drawer-panel]').forEach(el=>el.hidden=el.dataset.drawerPanel!==panel);
 if(panel==='Businesses'){const next=BUSINESSES.find(b=>state.runEarned<b.unlock);for(const b of BUSINESSES){const unlocked=state.runEarned>=b.unlock,q=quote(state,productionStatus(state).model,b.id),selected=b.id===state.business;row(`business-${b.id}`,all||unlocked||b===next,selected,selected?0:unlocked?1:2);text(`business-${b.id}-detail`,unlocked?(q.available?`${money(q.payout)} payout · ${q.duration.toFixed(1)}s`:q.reason):`Unlocks at ${money(b.unlock)} earned`);updateButton('business',b.id,selected?'Selected':unlocked?'Select':'Locked',!unlocked||selected,selected);}}
 if(panel==='Models'){const previews=MODELS.map(m=>({m,preview:modelPreview(state,m.id)})),next=previews.filter(x=>!x.preview.quote.available).sort((a,b)=>a.m.unlock-b.m.unlock)[0];for(const {m,preview} of previews){const q=preview.quote,selectable=state.runEarned>=m.unlock&&q.vram<=capacity(state),selected=state.model===m.id&&state.routing==='manual';row(`model-${m.id}`,all||q.available||selected||m===next?.m,selected,selected?0:q.available?1:2);text(`model-${m.id}-net`,q.available?`${money(q.net)}/s per worker · ${preview.delta>=0?'+':''}${money(preview.delta)}/s change`:'Unavailable for this business');text(`model-${m.id}-detail`,!q.available?(q.vram>capacity(state)?`Needs ${q.vram} GB; your rig has ${capacity(state)} GB.`:q.reason):`${money(q.cost)} / job${m.vram?` · ${q.vram} GB per worker`:''}`);hidden(`model-${m.id}-quant`,!q.quantized);updateButton('model',m.id,selected?'Selected':preview.clearsRouting?'Use this model · turn off routing':m.vram?'Load model':'Use model',!selectable||selected,selected);}}
 if(panel==='Rig'){const current=GPUS.findIndex(g=>g.id===state.gpu);text('rig-capacity',`${state.jobs.reduce((n,j)=>n+j.vram,0)} / ${capacity(state)} GB`);text('rig-heat',`${Math.round(state.heat)}°C`);text('rig-watts',`${GPUS[current]?.watts??0} W / worker`);GPUS.forEach((g,i)=>{row(`gpu-${g.id}`,all||i===current||i===current+1,i===current,i===current?0:1);updateButton('gpu',g.id,i===current?'Installed':i<current?'Owned':money(g.cost),i<=current||state.cash<g.cost,i===current);});updateButton('harness','quantization',has(state,'quantization')?'Installed':'$300',has(state,'quantization')||state.cash<300);for(const u of UPGRADES.filter(u=>u.kind==='cool'))updateUpgrade(u.id,'rig',all);}
 if(panel==='Upgrades')for(const u of UPGRADES.filter(u=>u.kind!=='cool'))updateUpgrade(u.id,'all',all);
 if(panel==='Agents'){text('claw-description',state.claw?'Workers share your hardware. Check costs before adding another.':state.runEarned<8000?'Available at $8,000 earned this run.':'Install the harness to add workers and model routing.');updateButton('claw','',state.claw?'Installed':'Install · $2,400',state.claw||state.runEarned<8000||state.cash<2400);text('worker-count',`${state.workers} / 4 workers`);updateButton('worker','',state.workers>=4?'Fully staffed':`Add worker · ${money(WORKER_PRICES[state.workers])}`,!state.claw||state.workers>=4||state.cash<WORKER_PRICES[state.workers]);for(const route of ['manual','cheapest','margin','local']){const b=document.querySelector<HTMLButtonElement>(`[data-action=routing][data-id=${route}]`)!;b.disabled=!state.claw||!has(state,'routing');b.classList.toggle('selected',state.routing===route);b.setAttribute('aria-pressed',String(state.routing===route));}text('routing-hint',has(state,'routing')?'Routing applies to new jobs.':'Install Model routing below to enable presets.');for(const h of HARNESS.filter(h=>h.id!=='quantization'))updateButton('harness',h.id,has(state,h.id)?'Installed':money(h.cost),has(state,h.id)||state.cash<h.cost||!state.claw);}
 if(panel==='Funding'){text('funding-round',state.prestige>=3?'FREE PLAY':`ROUND ${state.prestige+1} OF 3`);text('funding-name',p.name);text('funding-copy',state.prestige===0?'Prove the work sells. Nobody in the meeting asks who used to do it.':state.prestige===1?'The pitch calls it scale. The bedroom calls it a fire hazard.':'Offer the public a stake in the mess. Keep the nice photographs for the prospectus.');text('funding-earned',money(state.runEarned));text('funding-target',` / ${money(p.target)} earned`);width('funding-progress',state.runEarned/p.target*100);text('funding-reward',`+${p.reward} UV`);updateButton('raise','',p.eligible?'Raise funding ↗':'Keep earning',!p.eligible);hidden('permanent-perks',state.prestige<1);text('valuation',`${state.valuation} UV`);const next=PERKS.find(x=>x.tier>state.prestige);for(const perk of PERKS){const owned=state.perks.includes(perk.id);row(`perk-${perk.id}`,all||(!owned&&perk.tier<=state.prestige)||perk===next,owned,owned?3:perk.tier);updateButton('perk',perk.id,owned?'Owned':`${perk.cost} UV`,owned||state.valuation<perk.cost||state.prestige<perk.tier,owned);}text('lifetime',`Lifetime: ${number(state.totalSlop)} published · ${money(state.totalEarned)} earned · ${state.discovered.length}/40 events discovered`);}
}
function updateUpgrade(id:string,place:string,all:boolean){const u=UPGRADES.find(u=>u.id===id)!,owned=state.upgrades.includes(id),previous=!u.rank||state.upgrades.includes(`${u.kind}-${u.rank-1}`);row(`${place}-upgrade-${id}`,all||(!owned&&previous),owned,u.rank);updateButton('upgrade',id,owned?'Owned':money(u.cost),owned||!previous||state.cash<u.cost,owned);}
function openDrawer(name:Drawer,opener?:HTMLElement){if(!$<HTMLDialogElement>('drawer').open){drawerOpener=opener??document.activeElement as HTMLElement;ui.drawer=name;updateDrawer();$<HTMLDialogElement>('drawer').showModal();}else{ui.drawer=name;updateDrawer();}$('drawer-body').scrollTop=0;$('drawer-heading').focus({preventScroll:true});}
function closeDrawer(){const dialog=$<HTMLDialogElement>('drawer');if(dialog.open)dialog.close();}
$<HTMLDialogElement>('drawer').addEventListener('close',()=>{ui.drawer=null;if(drawerOpener?.isConnected)drawerOpener.focus({preventScroll:true});});
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement){e.target.hidden=true;e.target.closest('.illustrated-icon')?.classList.add('failed');}},true);
document.querySelectorAll<HTMLDetailsElement>('details[data-disclosure]').forEach(el=>el.addEventListener('toggle',()=>{ui.disclosures[el.dataset.disclosure!]=el.open;if(ui.drawer)updateDrawer();}));
function save(){if(preserveInvalidSave)return;try{localStorage.setItem(SAVE_KEY,encodeSave(state,Math.max(lastWall,Date.now())));saveWarning='';}catch{saveWarning='Local saving failed. Export a save before you close the game.';}}
function sync(){const step=clockStep(lastWall,Date.now());advance(state,step.seconds);lastWall=step.next;}
function announce(message:string){text('announcement',message);}
function act(a:Action){sync();const r=dispatch(state,a);announce(r.message);if(r.ok){preserveInvalidSave=false;save();sound();}render();}
function modal(html:string){const dialog=$<HTMLDialogElement>('dialog'),alreadyOpen=dialog.open;if(!alreadyOpen)modalOpener=document.activeElement as HTMLElement;$('dialog-body').innerHTML=html;if(!alreadyOpen)dialog.showModal();else dialog.querySelector<HTMLElement>('button,input,textarea')?.focus({preventScroll:true});}
$<HTMLDialogElement>('dialog').addEventListener('close',()=>{if(modalOpener?.isConnected)modalOpener.focus({preventScroll:true});});
function confirmModal(html:string){confirmationOpener=document.activeElement as HTMLElement;$('confirmation-body').innerHTML=html;$<HTMLDialogElement>('confirmation').showModal();}
$<HTMLDialogElement>('confirmation').addEventListener('close',()=>{const parent=confirmationOpener?.closest('dialog');if(confirmationOpener?.isConnected&&(!parent||parent.open)&&!(confirmationOpener instanceof HTMLButtonElement&&confirmationOpener.disabled))confirmationOpener.focus({preventScroll:true});else if($<HTMLDialogElement>('drawer').open)$('drawer-heading').focus({preventScroll:true});});
const closeButton='<button data-close class="secondary">Back to the bedroom</button>';
function showEnding(){modal(`<span class="label">THE EXIT</span><h2 id="modal-heading">AGI Achieved:<br><em>It Rewrote Your LinkedIn Bio.</em></h2><p>Three funding rounds. ${number(state.totalSlop)} posts. A room you can no longer sleep in.</p><p>The shareholders got their return. The people whose work made this possible got a webinar about reskilling. Your plant didn’t make it.</p><div class="ending-stats">${money(state.totalEarned)} earned · ${clock(state.totalSeconds)} spent building</div><p>The main game is complete. Keep producing, collect the remaining events, and raise again.</p>${closeButton}`);}
function raiseDialog(){const p=prestigeQuote(state);if(!p.eligible)return;confirmModal(`<span class="label">${p.name.toUpperCase()}</span><h2 id="confirmation-heading">Raise funding and reset this run?</h2><p>You’ll receive <strong>${p.reward} Unjustified Valuation</strong> for permanent upgrades.</p><div class="confirm-box"><strong>Reset:</strong> cash, rig, models, workers, businesses and regular upgrades.<br><strong>Keep:</strong> permanent perks, discoveries and lifetime stats.</div><p>Starting perks apply to the new run. Unfinished jobs are abandoned.</p><div class="modal-buttons"><button id="confirm-raise" class="primary">Raise ${p.name} ↗</button><button data-close class="secondary">Not yet</button></div>`);}
function settingsDialog(){modal(`<span class="label">SETTINGS</span><h2 id="modal-heading">Settings</h2><label class="setting-row"><span>Sound <small>Quiet purchase sounds. No background music.</small></span><input id="sound-toggle" type="checkbox" ${!state.muted?'checked':''}></label><label class="setting-row"><span>Reduce motion <small>Freeze monitor glow, hardware lights and purchase fades.</small></span><input id="motion-toggle" type="checkbox" ${state.reducedMotion?'checked':''}></label><h3 class="subheading">Save data</h3><p>Saves stay in this browser. Offline production counts up to two hours.</p><div class="modal-buttons"><button id="export-save" class="secondary">Export save</button><button id="import-save" class="secondary">Import save</button></div><textarea id="save-text" aria-label="Save data" placeholder="Paste exported save data here to import it."></textarea><p id="save-result" role="status"></p><div class="modal-buttons">${closeButton}<button id="reset-save" class="text-button danger">Reset everything</button></div>`);}
function aboutDialog(){modal(`<span class="label">BEDROOM AGI</span><h2 id="modal-heading">How to play</h2><p>Generate two articles and buy automatic production for $25. Then check in every few minutes to buy upgrades, switch models and choose more profitable work.</p><p>Businesses and models unlock as you earn. View rig to buy GPUs, cooling and quantization. SlopClaw adds workers and routing; extra workers share your hardware and add running costs.</p><p>Funding resets the run and awards permanent valuation. The first round takes about 3–4 hours with regular check-ins. Three rounds finish the story.</p><p class="fine-print">Everything runs in your browser. Prices, models, performance figures and executive dialogue are fictional satire. No AI services are connected.</p>${closeButton}`);}
let audio:AudioContext|undefined;
function sound(){if(state.muted)return;try{audio??=new AudioContext();void audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sine';osc.frequency.setValueAtTime(620,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(920,audio.currentTime+.08);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.12);osc.start();osc.stop(audio.currentTime+.13);}catch{/* Audio is optional. */}}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{announce('This browser doesn’t support fullscreen here.');}}
document.addEventListener('click',e=>{
 const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;if(b.dataset.drawer){openDrawer(b.dataset.drawer as Drawer,b);return;}
 if(b.dataset.action){const type=b.dataset.action;if(type==='raise'){raiseDialog();return;}if(type==='recover'){if(state.routing!=='manual')act({type:'routing',id:'manual'});act({type:'business',id:'seo'});act({type:'model',id:'starter'});return;}if(type==='model'&&state.routing!=='manual')act({type:'routing',id:'manual'});act({type:type==='generate-extra'?'generate':type,id:b.dataset.id} as Action);return;}
 if(b.hasAttribute('data-close')){b.closest('dialog')?.close();return;}switch(b.id){case 'close-drawer':closeDrawer();break;case 'settings':settingsDialog();break;case 'about':aboutDialog();break;case 'dismiss-offline':offlineSummary='';saveWarning='';render();break;
 case 'confirm-raise':$<HTMLDialogElement>('confirmation').close();resetRoomTransitions();act({type:'prestige'});break;
 case 'export-save':{sync();save();const raw=encodeSave(state,Date.now());$<HTMLTextAreaElement>('save-text').value=raw;const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bedroom-agi-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);text('save-result','Save exported. The text is also below.');break;}
 case 'import-save':{const raw=$<HTMLTextAreaElement>('save-text').value,saved=decodeSave(raw,Date.now());if(!saved){text('save-result','That save doesn’t look right. Your current game is unchanged.');break;}confirmModal(`<span class="label">IMPORT SAVE</span><h2 id="confirmation-heading">Replace this run?</h2><p>This replaces your current progress with the pasted save. Export your current game first if you want to keep it.</p><div class="modal-buttons"><button id="confirm-import" class="primary">Replace current save</button><button data-close class="secondary">Cancel</button></div>`);$('confirm-import').onclick=()=>{const parsed=decodeSave(raw,Date.now())!;state=parsed.state;advance(state,parsed.offlineSeconds);endingShown=state.ending;lastWall=Math.max(Date.now(),parsed.savedAt);preserveInvalidSave=false;resetRoomTransitions();save();$<HTMLDialogElement>('confirmation').close();$<HTMLDialogElement>('dialog').close();render();announce('Save imported.');};break;}
 case 'reset-save':confirmModal(`<span class="label">RESET EVERYTHING</span><h2 id="confirmation-heading">Delete all progress?</h2><p>Cash, hardware, prestige, permanent upgrades and discoveries will be erased. Export your save first if you might want it back.</p><div class="modal-buttons"><button id="confirm-reset" class="primary danger">Delete all progress</button><button data-close class="secondary">Cancel</button></div>`);$('confirm-reset').onclick=()=>{state=createGame();endingShown=false;offlineSummary='';lastWall=Date.now();preserveInvalidSave=false;resetRoomTransitions();save();$<HTMLDialogElement>('confirmation').close();$<HTMLDialogElement>('dialog').close();closeDrawer();render();};break;}
});
document.addEventListener('change',e=>{const input=e.target as HTMLInputElement;if(input.id==='sound-toggle'){state.muted=!input.checked;save();sound();}if(input.id==='motion-toggle'){state.reducedMotion=input.checked;save();render();}});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='f'&&!$<HTMLDialogElement>('dialog').open&&!$<HTMLDialogElement>('drawer').open&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();void fullscreen();}});
document.addEventListener('visibilitychange',()=>{sync();save();render();});window.addEventListener('pagehide',()=>{sync();save();});
window.advanceTime=(ms:number)=>{sync();advance(state,ms/1000);lastWall=Math.max(lastWall,Date.now());render();drawRoom($<HTMLCanvasElement>('room'),state,performance.now());};
window.render_game_to_text=()=>JSON.stringify({coordinateSystem:'Room canvas: 720 by 480 logical units; origin top-left, x right, y down; controls in HTML.',room:roomStatus(state),tab:legacyTab(ui.drawer),ui:{drawer:ui.drawer,disclosures:{...ui.disclosures},productionStatus:productionStatus(state).kind,suggestedIDs:suggestedUpgrades(state).map(u=>u.id)},cash:state.cash,slop:state.slop,totalSlop:state.totalSlop,runEarned:state.runEarned,seconds:state.seconds,prestige:state.prestige,valuation:state.valuation,ending:state.ending,auto:state.auto,claw:state.claw,workers:state.workers,model:state.model,business:state.business,routing:state.routing,gpu:state.gpu,vram:capacity(state),heat:state.heat,income:income(state),jobs:state.jobs,upgrades:state.upgrades,harness:state.harness,perks:state.perks,notice:state.notice,funding:prestigeQuote(state)});
setInterval(()=>{sync();render();},500);setInterval(()=>{sync();if(!saveWarning)save();},10000);
let lastFrame=0;function frame(now:number){if(!document.hidden&&now-lastFrame>=1000/30){drawRoom($<HTMLCanvasElement>('room'),state,now);lastFrame=now;}requestAnimationFrame(frame);}render();requestAnimationFrame(frame);
