import './style.css';
import {createGame,advance,dispatch,quote,income,capacity,stage,prestigeQuote,has,chooseModel} from './engine';
import {MODELS,BUSINESSES,GPUS,UPGRADES,HARNESS,PERKS,NEWS,STAGES,FUNDING,WORKER_PRICES} from './content';
import {encodeSave,decodeSave,clockStep} from './save';
import {drawRoom,roomStatus} from './room';
import type {GameState,Action,Routing} from './types';

declare global {interface Window {advanceTime:(ms:number)=>void;render_game_to_text:()=>string}}
const SAVE_KEY='bedroom-agi-v1';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n>=100?0:2}).format(n);
const number=(n:number)=>Math.floor(n).toLocaleString('en-US');
const clock=(n:number)=>`${Math.floor(n/3600).toString().padStart(2,'0')}:${Math.floor(n/60%60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const icons:Record<string,string>={chip:'M5 5h14v14H5z M9 9h6v6H9z M9 2v3m6-3v3M9 19v3m6-3v3M2 9h3m-3 6h3m14-6h3m-3 6h3',folder:'M3 6h7l2 2h9v12H3z',arrow:'M5 12h14m-5-5 5 5-5 5',bolt:'m13 2-9 12h7l-1 8 10-12h-7z',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6 7 7m10 10 1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4',check:'m4 12 5 5L20 6',fullscreen:'M3 9V3h6m6 0h6v6M3 15v6h6m6 0h6v-6',claw:'M6 3v5l4 4-4 4v5m12-18v5l-4 4 4 4v5M10 12h4',coin:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20 M15 7H10a3 3 0 0 0 0 6h4a2 2 0 0 1 0 4H8m4-12v14',work:'M4 6h16v12H4z M8 3v3m8-3v3M8 10h8m-8 4h5'};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${(icons[name]??icons.chip).split(' M').map((p,i)=>`<path d="${i?'M':''}${p}"/>`).join('')}</svg>`;
let state=createGame(),tab='Work',lastWall=Date.now(),offlineSummary='',saveWarning='',announcement='',endingShown=false,preserveInvalidSave=false;
try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const saved=decodeSave(raw,Date.now());if(saved){state=saved.state;lastWall=Math.max(lastWall,saved.savedAt);const before=state.cash,slop=state.slop;advance(state,saved.offlineSeconds);if(saved.offlineSeconds>30)offlineSummary=`While you were away: ${number(state.slop-slop)} posts, ${money(state.cash-before)} net. ${Math.round(saved.offlineSeconds/60)} minutes counted (two-hour cap).`;}else {preserveInvalidSave=true;saveWarning='Your old save couldn’t be read. A fresh run is ready; the old save has been kept until you make a move.';}}}
catch{saveWarning='This browser won’t let us save locally. Export your save before closing.';}
if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)state.reducedMotion=true;

document.querySelector('#app')!.innerHTML=`
 <header class="site-header"><a class="wordmark" href="#" aria-label="Bedroom AGI home">${icon('chip')} BEDROOM INDUSTRIES<span class="tiny">one room · no employees</span></a><div class="header-tools"><span class="local-badge"><i></i> Runs on your machine</span><button id="fullscreen" class="icon-button" aria-label="Toggle fullscreen">${icon('fullscreen')}</button><button id="settings" class="icon-button" aria-label="Open settings">${icon('gear')}</button></div></header>
 <main><section class="hero"><div><div class="eyebrow"><span class="label">IDLE GAME</span><span>FICTIONAL INDUSTRY. REAL BAD IDEAS.</span></div><h1>Bedroom <em>AGI.</em><span class="title-star">✳</span></h1><p>Your clients save on staff. You spend it on GPUs.</p></div><div class="run-stamp"><span id="run-label">BOOTSTRAPPED</span><strong id="run-clock">00:00:00</strong><span>time this run</span></div></section>
 <section class="stats" aria-label="Business statistics"><div class="stat cash-stat"><span>CASH ON HAND</span><strong id="cash"></strong><small>The savings went somewhere.</small></div><div class="stat"><span>NET INCOME / SEC</span><strong id="net"></strong><small id="income-detail"></small></div><div class="stat"><span>SLOP PUBLISHED</span><strong id="slop"></strong><small id="slop-detail">Pages, posts, pictures and videos.</small></div><div class="stat"><span>NEXT FUNDING ROUND</span><strong id="funding-name"></strong><div class="funding-line"><div class="meter"><i id="funding-progress"></i></div><small id="funding-percent"></small></div></div></section>
 <div id="offline" class="offline" hidden></div>
 <div class="game-layout"><aside class="room-column"><section class="room-card"><div class="section-bar"><span><span class="status-dot"></span> YOUR BEDROOM</span><span class="micro">NIGHT SHIFT</span></div><canvas id="room" width="720" height="480" role="img" aria-label="An illustrated bedroom with a person at a laptop"></canvas><div class="room-caption"><div><span id="stage-index" class="micro"></span><h2 id="stage-name"></h2></div><span id="rig-badge" class="pill"></span></div><div class="room-meters"><div><span>TEMPERATURE</span><strong id="heat"></strong><div class="meter"><i id="heat-progress"></i></div></div><div><span>VRAM IN USE</span><strong id="vram"></strong><div class="meter"><i id="vram-progress"></i></div></div></div><p id="room-hint" class="room-hint"></p></section>
 <section class="news-card"><div class="section-bar"><span>FROM THE FEED</span><span id="news-kind" class="micro">fictional industry updates</span></div><div id="news"></div></section>
 <section class="terminal"><div class="terminal-heading"><span><i></i> activity.log</span><span id="log-status">waiting for something to happen</span></div><div id="feed"></div><div class="terminal-prompt">bedroom@localhost <span>~</span> $ <i></i></div></section></aside>
 <section class="desktop"><div class="window-bar"><div>${icon('folder')} <span>slopOS <small>— personal edition</small></span></div><div class="window-dots"><i></i><i></i><i></i></div></div><nav id="tabs" role="tablist" aria-label="Desktop apps"></nav><div id="panel" role="tabpanel"></div><div class="status-bar"><span><i></i> <span id="status-auto"></span></span><span id="status-model"></span></div></section></div>
 <footer><span>The company keeps the savings. Everybody else gets the progress.</span><span>Fictional prices, performance & executive dialogue. <button id="about">About / how to play ↗</button></span></footer></main>
 <dialog id="dialog"><div id="dialog-body"></div></dialog><div id="announcement" class="sr-only" aria-live="polite"></div>`;

function button(label:string,type:string,id='',disabled=false,cls='') {return `<button data-action="${type}" data-id="${id}" data-key="${type}-${id}" ${disabled?'disabled':''} class="${cls}">${label}</button>`;}
let tabSignature='';
function tabs(){const signature=tab+prestigeQuote(state).eligible;if(signature===tabSignature)return;tabSignature=signature;const names=['Work','Models','Hardware','SlopClaw','Funding'], symbols=['work','chip','bolt','claw','coin'];$('tabs').innerHTML=names.map((name,i)=>`<button role="tab" id="tab-${name}" aria-controls="panel" aria-selected="${tab===name}" tabindex="${tab===name?0:-1}" data-tab="${name}" class="${tab===name?'active':''}">${icon(symbols[i])}${name}${name==='Funding'&&prestigeQuote(state).eligible?'<i class="notification-dot"></i>':''}</button>`).join('');$('panel').setAttribute('aria-labelledby',`tab-${tab}`);}
function heading(kicker:string,title:string,description:string){return `<div class="panel-heading"><span class="micro">${kicker}</span><h2>${title}</h2><p>${description}</p></div>`;}
function upgradeList(){
 return `<div class="subheading"><h3>Upgrades</h3><span class="micro">${state.upgrades.length} / 24 BOUGHT</span></div><div class="upgrade-list">${(['speed','pay','cool','reach'] as const).map(kind=>{
  const u=UPGRADES.find(u=>u.kind===kind&&!state.upgrades.includes(u.id));if(!u)return `<div class="upgrade-row complete">${icon('check')}<div><strong>${{speed:'Speed',pay:'Payout',cool:'Cooling',reach:'Distribution'}[kind]} maxed out</strong><p>All upgrades purchased.</p></div></div>`;
  const benefit={speed:'15% faster production',pay:'20% added payout',cool:'More cooling',reach:'16% added payout'}[kind];
  return `<div class="upgrade-row"><span class="upgrade-symbol">${icon({speed:'bolt',pay:'coin',cool:'gear',reach:'arrow'}[kind])}</span><div><strong>${u.name}</strong><p>${u.description}</p><small>${benefit} · ${u.rank+1}/6</small></div>${button(money(u.cost),'upgrade',u.id,state.cash<u.cost,'buy-button')}</div>`;
 }).join('')}</div>`;
}
function workPanel(){
 const model=chooseModel(state,state.business),q=quote(state,model,state.business),busy=state.jobs.length>=state.workers;
 const selected=BUSINESSES.find(b=>b.id===state.business)!;
 return heading('01 / WORK','Production','Pick a business. Queue a job. It sells as soon as it’s done.')+
 `<div class="production-console"><div class="console-top"><span><i class="status-dot"></i> ${state.auto?'AUTOMATIC PRODUCTION':'MANUAL PRODUCTION'}</span><span>${state.workers} ${state.workers===1?'WORKER':'WORKERS'}</span></div><div class="production-title"><h3>${selected.name}</h3><span class="pill">${MODELS.find(m=>m.id===model)!.name}</span></div><div class="production-metrics"><div><span>TIME / JOB</span><strong>${q.duration.toFixed(1)}s</strong></div><div><span>PAYOUT</span><strong>${money(q.payout)}</strong></div><div><span>RUNNING COST</span><strong>${money(q.cost)}</strong></div></div>
 <div class="job-slots">${Array.from({length:state.workers},(_,i)=>{const j=state.jobs.find(j=>j.worker===i);return `<div class="job-slot"><span>${state.workers>1?`Worker ${i+1} · `:''}${j?`${BUSINESSES.find(b=>b.id===j.business)!.name} · ${j.remaining.toFixed(1)}s`:'Ready for a job'}</span><div class="meter"><i style="width:${j?(1-j.remaining/j.duration)*100:0}%"></i></div></div>`;}).join('')}</div>
 <div class="production-buttons">${button(`${icon('bolt')} ${busy?'Working on it…':'Generate slop'} ${icon('arrow')}`,'generate','',busy||!q.available||state.cash<q.cost,'primary')}${state.auto?'<span class="auto-label">✓ Automatically queued</span>':button('Automate · $25','auto','',state.cash<25,'secondary')}</div></div>
 <p class="hint">${esc(q.available?state.notice:q.reason)} ${!q.available?'<button data-action="recover">Use free chatbot + SEO</button>':''}</p>
 <div class="subheading"><h3>Businesses</h3><span class="micro">${BUSINESSES.filter(b=>state.runEarned>=b.unlock).length} / 4 UNLOCKED</span></div><div class="business-grid">${BUSINESSES.map(b=>{
 const unlocked=state.runEarned>=b.unlock,bq=quote(state,model,b.id),active=state.business===b.id;
 return `<button class="business-card ${active?'selected':''} ${!unlocked?'locked':''}" data-action="business" data-id="${b.id}" data-key="business-${b.id}" ${!unlocked?'disabled':''}><span class="business-icon">${b.icon}</span><span class="business-copy"><strong>${b.name}</strong><span>${b.description}</span><small>${unlocked?(bq.available?`${money(bq.payout)} / job · ${bq.duration.toFixed(1)}s`:'Needs a more capable model'):`Unlocks at ${money(b.unlock)} earned`}</small></span><span class="select-mark">${active?'✓':unlocked?'↗':'⌑'}</span></button>`;
 }).join('')}</div>`+upgradeList();
}
function modelsPanel(){
 return heading('02 / MODELS','Models','Estimates use your current business. Switching applies to the next job.')+
 `<div class="info-strip">${icon('work')} ${BUSINESSES.find(b=>b.id===state.business)!.name}<span>Expected net income per worker shown below</span></div><div class="model-list">${MODELS.map(m=>{
  const q=quote(state,m.id,state.business),unlocked=state.runEarned>=m.unlock,selectable=unlocked&&q.vram<=capacity(state),active=state.model===m.id;
  return `<article class="model-card ${active?'selected':''}"><div class="model-top"><span class="model-avatar ${m.vram?'local':'cloud'}">${m.vram?icon('chip'):m.id==='starter'?'_':m.company[0]}</span><div><h3>${m.name}</h3><small>${m.company}</small></div><span class="pill">${m.tag}${q.quantized?' · Q4':''}</span></div><p>${m.description}</p><div class="model-bottom"><div><strong class="${q.available?'positive':''}">${q.available?`${money(q.net)}/s`:'Unavailable'}</strong><small>${!selectable?esc(q.reason):!q.available?esc(q.reason):`${money(q.cost)} / job${m.vram?` · ${q.vram} GB VRAM`:''}`}</small>${q.quantized?'<small>Quantized: payout reduced by 18%.</small>':''}</div>${button(active?'Selected':m.vram?'Load model':'Use model','model',m.id,!selectable||active,active?'selected-button':'secondary')}</div></article>`;
 }).join('')}</div><p class="fine-print">These are fictional models and prices. No requests leave your browser. Local inference pays electricity per job; weight memory is reserved per worker.</p>`;
}
function hardwarePanel(){
 const current=GPUS.findIndex(g=>g.id===state.gpu);
 return heading('03 / HARDWARE','Hardware','Install a better rig to fit larger models and speed up local jobs.')+
 `<div class="hardware-summary"><div>${icon('chip')}<span>INSTALLED VRAM<strong>${capacity(state)} GB</strong></span></div><div>${icon('bolt')}<span>LOCAL LOAD<strong>${GPUS.find(g=>g.id===state.gpu)?.watts??0} W / worker</strong></span></div></div><div class="upgrade-list">${GPUS.map((g,i)=>`<div class="upgrade-row hardware-row ${i===current?'selected':''}"><span class="gpu-icon">${icon('chip')}</span><div><strong>${g.name}</strong><p>${g.description}</p><small>${g.vram} GB · ${g.speed}× local speed · ${g.watts} W</small></div>${button(i===current?'Installed':i<current?'Owned':money(g.cost),'gpu',g.id,i<=current||state.cash<g.cost,'buy-button')}</div>`).join('')}</div><div class="subheading"><h3>Memory and cooling</h3></div><div class="upgrade-list"><div class="upgrade-row"><span class="upgrade-symbol">Q4</span><div><strong>Quantization</strong><p>Halves VRAM when a model won’t fit. Payout drops 18%.</p></div>${button(has(state,'quantization')?'Installed':'$300','harness','quantization',has(state,'quantization')||state.cash<300,'buy-button')}</div>${UPGRADES.filter(u=>u.kind==='cool').map(u=>`<div class="upgrade-row"><span class="upgrade-symbol">${icon('gear')}</span><div><strong>${u.name}</strong><p>${u.description}</p><small>Cooling level ${u.rank+1} / 6</small></div>${button(state.upgrades.includes(u.id)?'Installed':money(u.cost),'upgrade',u.id,state.upgrades.includes(u.id)||state.cash<u.cost||(u.rank>0&&!state.upgrades.includes(`cool-${u.rank-1}`)),'buy-button')}</div>`).join('')}</div>`;
}
function clawPanel(){
 const locked=state.runEarned<8000;
 return heading('04 / AUTOMATION','SlopClaw','Install the harness to add workers, route jobs between models, and manage running costs.')+
 `<div class="claw-banner"><span class="claw-logo">${icon('claw')}</span><div><h3>${state.claw?'Your agents are online.':'Add automatic workers.'}</h3><p>${state.claw?'More workers share the rig and add coordination costs. Check your margins.':locked?'Available at $8,000 earned this run.':'Install SlopClaw to unlock workers, routing, and harness upgrades.'}</p></div>${!state.claw?button('Install · $2,400','claw','',locked||state.cash<2400,'primary'):'<span class="pill">INSTALLED</span>'}</div>
 <div class="worker-panel"><div><h3>${state.workers} / 4 workers</h3><p>Each worker gets a job. Each extra agent adds overhead.</p></div>${button(state.workers>=4?'Fully staffed':`Add worker · ${money(WORKER_PRICES[state.workers])}`,'worker','',!state.claw||state.workers>=4||state.cash<WORKER_PRICES[state.workers],'secondary')}</div>
 <div class="subheading"><h3>Model routing</h3><span class="micro">APPLIES TO NEW JOBS</span></div><div class="routing-grid">${([['manual','Your choice','Always use the selected model.'],['cheapest','Cheapest','Lowest affordable running cost.'],['margin','Highest margin','Best estimated net income per worker.'],['local','Local first','Prefer your own models; use cloud if needed.']] as const).map(([id,label,desc])=>`<button class="route-card ${state.routing===id?'selected':''}" data-action="routing" data-id="${id}" data-key="routing-${id}" ${!state.claw||!has(state,'routing')?'disabled':''}><strong>${label}</strong><span>${desc}</span></button>`).join('')}</div>
 <div class="subheading"><h3>Harness upgrades</h3><span class="micro">${state.harness.length} / 9 INSTALLED</span></div><div class="upgrade-list">${HARNESS.map(h=>`<div class="upgrade-row"><span class="upgrade-symbol">${icon('claw')}</span><div><strong>${h.name}</strong><p>${h.description}</p></div>${button(has(state,h.id)?'Installed':money(h.cost),'harness',h.id,has(state,h.id)||state.cash<h.cost||(!state.claw&&h.id!=='quantization'),'buy-button')}</div>`).join('')}</div>`;
}
function fundingPanel(){
 const p=prestigeQuote(state);
 return heading('05 / FUNDING','Funding','Raise funding, reset the operation, and keep your unjustified valuation.')+
 `<div class="funding-card"><div class="funding-top"><span class="label">${state.prestige>=3?'FREE PLAY':`ROUND ${state.prestige+1} OF 3`}</span><span>${state.prestige>=3?'You can keep raising.':'Permanent upgrades survive resets.'}</span></div><h3>${p.name}</h3><p>${state.prestige===0?'Prove the work sells. Nobody in the meeting asks who used to do it.':state.prestige===1?'The pitch calls it scale. The bedroom calls it a fire hazard.':'Offer the public a stake in the mess. Keep the nice photographs for the prospectus.'}</p><div class="funding-amount"><strong>${money(state.runEarned)}</strong><span> / ${money(p.target)} earned</span></div><div class="meter"><i style="width:${Math.min(100,state.runEarned/p.target*100)}%"></i></div><div class="funding-reward"><span>Valuation at this raise</span><strong>+${p.reward} UV</strong></div>${button(p.eligible?'Raise funding ↗':'Keep earning','raise','',!p.eligible,'primary')}<p class="fine-print">Resets cash, rig, businesses, models, workers and regular upgrades. Keeps permanent perks, discoveries and lifetime stats.</p></div>
 <div class="subheading"><h3>Unjustified valuation</h3><span class="valuation">${state.valuation} UV TO SPEND</span></div><p class="section-description">Production perks apply immediately. Starting equipment arrives next run.</p><div class="perk-grid">${PERKS.map(p=>`<article class="perk-card ${state.perks.includes(p.id)?'owned':''}"><span class="micro">${p.tier===1?'SEED ROUND':'SERIES A'}</span><h3>${p.name}</h3><p>${p.description}</p>${button(state.perks.includes(p.id)?'Owned':`${p.cost} UV`,'perk',p.id,state.perks.includes(p.id)||state.valuation<p.cost||state.prestige<p.tier,'secondary')}</article>`).join('')}</div><div class="lifetime"><span>LIFETIME</span><strong>${number(state.totalSlop)} posts · ${money(state.totalEarned)} earned · ${state.discovered.length}/40 events discovered</strong></div>`;
}
function render(){
 const rates=income(state),p=prestigeQuote(state),used=state.jobs.reduce((n,j)=>n+j.vram,0);
 $('cash').textContent=money(state.cash);$('net').textContent=`${rates.net>=0?'+':''}${money(rates.net)}`;$('income-detail').textContent=`${money(rates.revenue)} in / ${money(rates.cost)} out`;
 $('slop').textContent=number(state.slop);$('funding-name').textContent=p.name;$('funding-progress').style.width=`${Math.min(100,state.runEarned/p.target*100)}%`;$('funding-percent').textContent=`${Math.floor(state.runEarned/p.target*100)}%`;
 $('run-label').textContent=state.prestige?`${FUNDING[Math.min(state.prestige-1,2)].toUpperCase()} FUNDED`:'BOOTSTRAPPED';$('run-clock').textContent=clock(state.seconds);
 $('stage-index').textContent=`STAGE ${String(stage(state)+1).padStart(2,'0')} / 06`;$('stage-name').textContent=STAGES[stage(state)];$('rig-badge').textContent=state.gpu==='none'?'STOCK LAPTOP':`${capacity(state)} GB RIG`;
 $('heat').textContent=`${state.heat.toFixed(0)}°C`;$('heat-progress').style.width=`${(state.heat-20)/80*100}%`;$('heat-progress').classList.toggle('hot',state.heat>65);
 $('vram').textContent=`${used} / ${capacity(state)} GB`;$('vram-progress').style.width=`${capacity(state)?used/capacity(state)*100:0}%`;
 $('room-hint').textContent=state.heat>65?'Your local jobs are slowing down. Buy more cooling.':state.gpu==='none'?'Local models need a GPU. Buy one in Hardware.':state.jobs.some(j=>j.vram)?'Local jobs are running. Electricity is included in their running cost.':'The GPU is ready. Local models live in the Models tab.';
 const news=NEWS.find(n=>n.id===state.event)??NEWS.find(n=>n.id===state.discovered.at(-1));
 $('news').innerHTML=news?`<span class="news-eyebrow">${news.speaker?`${esc(news.speaker)} · FICTIONAL DIALOGUE`:'FICTIONAL INDUSTRY UPDATE'}</span><h3>${esc(news.title)}</h3><p>${esc(news.text)}</p>${state.eventLeft&&news.effect!=='none'?`<small>${news.effect==='demand'?'Payouts +15%':'Running costs +12%'} · ${Math.ceil(state.eventLeft)}s left</small>`:''}`:'<span class="news-eyebrow">YOUR FIRST BRIEF</span><h3>The work used to go to someone else.</h3><p>A client wants articles without paying a writer. You have a laptop and no questions about the arrangement.</p>';
 $('feed').innerHTML=state.feed.slice(0,5).map(f=>`<div class="log-line"><time>${clock(f.at)}</time><span class="${f.kind}">${esc(f.text)}</span></div>`).join('');$('log-status').textContent=state.jobs.length?`${state.jobs.length} job${state.jobs.length>1?'s':''} running`:'idle';
 $('status-auto').textContent=state.auto?'Production on':'Manual mode';$('status-model').textContent=MODELS.find(m=>m.id===rates.model)!.name;
 if(offlineSummary||saveWarning){$('offline').hidden=false;$('offline').innerHTML=`<span>${esc(offlineSummary||saveWarning)}</span><button id="dismiss-offline" aria-label="Dismiss message">×</button>`;}else $('offline').hidden=true;
 const active=document.activeElement as HTMLElement;const key=active?.dataset.key,oldTop=$('panel').scrollTop;
 $('panel').innerHTML=tab==='Work'?workPanel():tab==='Models'?modelsPanel():tab==='Hardware'?hardwarePanel():tab==='SlopClaw'?clawPanel():fundingPanel();
 $('panel').scrollTop=oldTop;if(key)$('panel').querySelector<HTMLElement>(`[data-key="${key}"]`)?.focus({preventScroll:true});
 tabs();drawRoom($<HTMLCanvasElement>('room'),state,performance.now());
 if(state.ending&&!endingShown){endingShown=true;showEnding();}
}
function save(){if(preserveInvalidSave)return;try{localStorage.setItem(SAVE_KEY,encodeSave(state,Math.max(lastWall,Date.now())));saveWarning='';}catch{saveWarning='Local saving failed. Export a save before you close the game.';}}
function sync(){const step=clockStep(lastWall,Date.now());advance(state,step.seconds);lastWall=step.next;}
function announce(message:string){announcement=message;$('announcement').textContent=message;}
function act(a:Action){sync();const r=dispatch(state,a);announce(r.message);if(r.ok){preserveInvalidSave=false;save();sound();}render();}
function modal(html:string){$('dialog-body').innerHTML=html;$<HTMLDialogElement>('dialog').showModal();}
const closeButton='<button data-close class="secondary">Back to the bedroom</button>';
function showEnding(){modal(`<span class="label">THE EXIT</span><h2>AGI Achieved:<br><em>It Rewrote Your LinkedIn Bio.</em></h2><p>Three funding rounds. ${number(state.totalSlop)} posts. A room you can no longer sleep in.</p><p>The shareholders got their return. The people whose work made this possible got a webinar about reskilling. Your plant didn’t make it.</p><div class="ending-stats">${money(state.totalEarned)} earned · ${clock(state.totalSeconds)} spent building</div><p class="fine-print">The main game is complete. You can keep producing, collect the remaining events, and raise again.</p>${closeButton}`);}
function raiseDialog(){const p=prestigeQuote(state);if(!p.eligible)return;modal(`<span class="label">${p.name.toUpperCase()}</span><h2>Raise funding and reset this run?</h2><p>You’ll receive <strong>${p.reward} Unjustified Valuation</strong> for permanent upgrades.</p><div class="confirm-box"><strong>Reset:</strong> cash, rig, models, workers, businesses and regular upgrades.<br><strong>Keep:</strong> permanent perks, discoveries and lifetime stats.</div><p>Starting perks apply to the new run. Any unfinished jobs are abandoned.</p><div class="modal-buttons"><button id="confirm-raise" class="primary">Raise ${p.name} ↗</button><button data-close class="secondary">Not yet</button></div>`);}
function settingsDialog(){modal(`<span class="label">SETTINGS</span><h2>Settings</h2><label class="setting-row"><span>Sound <small>Quiet purchase sounds. No background music.</small></span><input id="sound-toggle" type="checkbox" ${!state.muted?'checked':''}></label><label class="setting-row"><span>Reduce motion <small>Freeze monitor glow and hardware lights.</small></span><input id="motion-toggle" type="checkbox" ${state.reducedMotion?'checked':''}></label><div class="subheading"><h3>Save data</h3></div><p>Saves stay in this browser. Offline production counts up to two hours.</p><div class="modal-buttons"><button id="export-save" class="secondary">Export save</button><button id="import-save" class="secondary">Import save</button></div><textarea id="save-text" aria-label="Save data" placeholder="Paste exported save data here to import it."></textarea><p id="save-result" role="status"></p><div class="modal-buttons">${closeButton}<button id="reset-save" class="text-button danger">Reset everything</button></div>`);}
function aboutDialog(){modal(`<span class="label">BEDROOM AGI</span><h2>How to play</h2><p>Generate two articles and buy automatic production for $25. After that, check in every few minutes to buy upgrades, switch models and pick more profitable work.</p><p>Businesses and models unlock as you earn. GPUs make local models available; SlopClaw adds workers and routing. Keep an eye on running costs and heat.</p><p>Funding resets the run and awards permanent valuation. The first round is balanced for about 3–4 hours with regular check-ins. Three funding rounds finish the story.</p><p class="fine-print">Everything runs in your browser. All prices, models, performance figures and executive dialogue are fictional satire. No AI services are connected.</p>${closeButton}`);}
let audio:AudioContext|undefined;
function sound(){if(state.muted)return;try{audio??=new AudioContext();void audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sine';osc.frequency.setValueAtTime(620,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(920,audio.currentTime+.08);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.12);osc.start();osc.stop(audio.currentTime+.13);}catch{/* Audio is optional. */}}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{announce('This browser doesn’t support fullscreen here.');}}
document.addEventListener('click',e=>{
 const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;
 if(b.dataset.tab){tab=b.dataset.tab;render();$(`tab-${tab}`).focus();return;}
 if(b.dataset.action){const type=b.dataset.action;if(type==='raise'){raiseDialog();return;}if(type==='recover'){act({type:'business',id:'seo'});act({type:'model',id:'starter'});return;}act({type,id:b.dataset.id} as Action);return;}
 if(b.hasAttribute('data-close')){$<HTMLDialogElement>('dialog').close();return;}
 switch(b.id){
 case 'settings':settingsDialog();break;
 case 'about':aboutDialog();break;
 case 'fullscreen':void fullscreen();break;
 case 'dismiss-offline':offlineSummary='';saveWarning='';render();break;
 case 'confirm-raise':$<HTMLDialogElement>('dialog').close();act({type:'prestige'});break;
 case 'export-save':{
  sync();save();const raw=encodeSave(state,Date.now());$<HTMLTextAreaElement>('save-text').value=raw;
  const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bedroom-agi-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-result').textContent='Save exported. The text is also below.';break;
 }
 case 'import-save':{
  const saved=decodeSave($<HTMLTextAreaElement>('save-text').value,Date.now());if(!saved){$('save-result').textContent='That save doesn’t look right. Your current game is unchanged.';break;}
  const raw=$<HTMLTextAreaElement>('save-text').value;modal(`<span class="label">IMPORT SAVE</span><h2>Replace this run?</h2><p>This will replace your current progress with the pasted save. Export your current game first if you want to keep it.</p><div class="modal-buttons"><button id="confirm-import" class="primary">Replace current save</button><button data-close class="secondary">Cancel</button></div>`);
  $('confirm-import').onclick=()=>{const parsed=decodeSave(raw,Date.now())!;state=parsed.state;advance(state,parsed.offlineSeconds);endingShown=state.ending;lastWall=Math.max(Date.now(),parsed.savedAt);preserveInvalidSave=false;save();$<HTMLDialogElement>('dialog').close();render();announce('Save imported.');};break;
 }
 case 'reset-save':modal(`<span class="label">RESET EVERYTHING</span><h2>Delete all progress?</h2><p>Cash, hardware, prestige, permanent upgrades and discoveries will be erased. Export your save first if you might want it back.</p><div class="modal-buttons"><button id="confirm-reset" class="primary danger">Delete all progress</button><button data-close class="secondary">Cancel</button></div>`);$('confirm-reset').onclick=()=>{state=createGame();endingShown=false;offlineSummary='';lastWall=Date.now();preserveInvalidSave=false;save();$<HTMLDialogElement>('dialog').close();tab='Work';render();};break;
 }
});
document.addEventListener('change',e=>{const input=e.target as HTMLInputElement;if(input.id==='sound-toggle'){state.muted=!input.checked;save();sound();}if(input.id==='motion-toggle'){state.reducedMotion=input.checked;save();render();}});
$('tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const list=['Work','Models','Hardware','SlopClaw','Funding'];let i=list.indexOf(tab);i=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowRight'?1:4))%5;tab=list[i];render();$(`tab-${tab}`).focus();});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='f'&&!$<HTMLDialogElement>('dialog').open&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();void fullscreen();}});
document.addEventListener('visibilitychange',()=>{sync();save();render();});window.addEventListener('pagehide',()=>{sync();save();});
window.advanceTime=(ms:number)=>{sync();advance(state,ms/1000);lastWall=Math.max(lastWall,Date.now());render();};
window.render_game_to_text=()=>JSON.stringify({coordinateSystem:'Room canvas: 720 by 480 logical units; origin top-left, x right, y down; controls in HTML.',room:roomStatus(state),tab,cash:state.cash,slop:state.slop,totalSlop:state.totalSlop,runEarned:state.runEarned,seconds:state.seconds,prestige:state.prestige,valuation:state.valuation,ending:state.ending,auto:state.auto,claw:state.claw,workers:state.workers,model:state.model,business:state.business,routing:state.routing,gpu:state.gpu,vram:capacity(state),heat:state.heat,income:income(state),jobs:state.jobs,upgrades:state.upgrades,harness:state.harness,perks:state.perks,notice:state.notice,funding:prestigeQuote(state)});
setInterval(()=>{sync();render();},500);setInterval(()=>{sync();if(!saveWarning)save();},10000);
render();
